### ISSUE TITLE
 On macOS with the Metal renderer, memory leaks occur every frame. Within just 3 minutes, memory usage in a basic app reached 6 GB.

### ISSUE THREAD

**Issue by manojsiddoji** [LukasBanana/LLGL#135] opened 2024-11-12 10:21 UTC

**Comment by LukasBanana** [comment] 2024-11-13 04:22
I'm closing this as a duplicate of #129. Please share any more details you can provide in that thread.
I submitted two commits that should mitigate this, but I can still see about 0.1 MB of leaked memory every 3 seconds. Unfortunately, my Mac is showing his age and the Debug Memory Hierarchy doesn't work in my Xcode 11 installation.

**Closed by LukasBanana** 2024-11-13 04:22 UTC
Labels: duplicate
